### ISSUE TITLE
请问这个有没有arm64版本

### ISSUE THREAD

**Issue by Dreamail** [lovechoudoufu/wechat_for_linux#1]
如题

**Comment by lovechoudoufu** [comment]
这个没有，uos商店那个好像有，可以找找看

**Comment by lovechoudoufu** [comment]
https://www.cnxclm.com/forum.php?mod=viewthread&tid=3059&ordertype=1
![image](https://user-images.githubusercontent.com/95681496/149071708-7ee8f21e-212f-4b37-8ffa-191ee750b8d1.png)
这里有其他版本的，但是我没有适用过。

**Comment by Dreamail** [comment]
好的谢谢

**Comment by Bajiangyue** [comment]
![image](https://github.com/lovechoudoufu/wechat_for_linux/assets/49513154/8e6d3017-8955-41e0-9958-bcbb284383cb)
这篇帖子要付费看了，有其他链接吗？

**Comment by Bajiangyue** [comment]
![image](https://github.com/lovechoudoufu/wechat_for_linux/assets/49513154/8e6d3017-8955-41e0-9958-bcbb284383cb)
这篇帖子要付费看了，有其他链接吗？
