### ISSUE TITLE
今天突然不能登陆了

### ISSUE THREAD

**Issue by CSWellesSun** [lovechoudoufu/wechat_for_linux#18]
之前都能在 Ubuntu22.04 上使用，但是今天登陆出现如下问题：
![image](https://github.com/lovechoudoufu/wechat_for_linux/assets/83463505/f0b8b8b1-4665-4d16-bd7b-b25244fb0e72)

**Comment by gondmhd** [comment]
我也碰到了 解决了吗

**Comment by CSWellesSun** [comment]
没有解决 又回归了没微信的日子

**Comment by DLWangSan** [comment]
我也碰到了，瞬间崩溃

**Comment by DLWangSan** [comment]
更新到1.0.0.238版本，已解决！

**Comment by lovechoudoufu** [comment]
> 更新到1.0.0.238版本，已解决！

这个版本可登陆

**Comment by lovechoudoufu** [comment]
238版本发到git了，自行下载。
https://github.com/lovechoudoufu/wechat_for_linux/releases/tag/wechat-beta_1.0.0.238_amd64
