### ISSUE TITLE
 wechat-beta_1.0.0.238_amd64_login.deb版本经测试在debian 12.5使用正常

### ISSUE THREAD

**Issue by ehongping** [lovechoudoufu/wechat_for_linux#19]
不是为了反映问题，而是为了赞美！
苦于Q厂没有提供LINUX版本下载，造成在LINUX系统使用WX很不方便。今天下载这个版本，扫码登录显示仅支持文件传输，登录后发现可以发信息，可以截图，用起来不错哟。
明明做得很强大，为啥那么低调，是怕收到传票？

**Comment by lovechoudoufu** [comment]
这个就是官方开发的客户端，我只不过搬运过来而已。
