### ISSUE TITLE
ubuntu 22.04 cant log in 登陆失败

### ISSUE THREAD

**Issue by houhuawei23** [lovechoudoufu/wechat_for_linux#2]
using phone to scan, cant log in. 登陆失败

**Comment by lovechoudoufu** [comment]
我使用wechat-beta_1.0.0.145_amd64.deb是可以手机扫码登录成功的。要不你让别人扫扫试试？

**Comment by Ye-Ethan** [comment]
> using phone to scan, cant log in. 登陆失败

参考https://bbs.deepin.org/post/209155

**Comment by lovechoudoufu** [comment]
已经更新绕过登录检测的版本：https://github.com/lovechoudoufu/wechat_for_linux/releases/tag/wechat-beta-%E7%BB%95%E8%BF%87%E7%99%BB%E5%BD%95%E6%A3%80%E6%B5%8B
