### ISSUE TITLE
wechat-beta_1.0.0.238_amd64_login在Debain12.2分辨率显示异常

### ISSUE THREAD

**Issue by muyiacc** [lovechoudoufu/wechat_for_linux#20]
# 系统环境
`
Linux version 6.1.0-13-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)
`

GUN/Linux 12信息
操作系统： Debian GNU/Linux 12
KDE Plasma 版本： 5.27.5
KDE 程序框架版本： 5.103.0
Qt 版本： 5.15.8
内核版本： 6.1.0-13-amd64 (64 位)
图形平台： Wayland
处理器： 8 × AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
内存： 14.5 GiB 内存
图形处理器： AMD Radeon Vega 8 Graphics
制造商： LENOVO
产品名称： 81XD
系统版本： Lenovo XiaoXinPro-13API 2019

微信界面：
![Snipaste_2024-06-15_21-59-54](https://github.com/lovechoudoufu/wechat_for_linux/assets/115904774/005d3d0e-e6f5-43fa-90ad-c6516ad80f8d)

有人一样的问题吗？仓库作者大大更新了请踢一下我，感谢

**Comment by PencilCore** [comment]
env QT_SCALE_FACTOR=2 /usr/bin/wechat 
即可

**Comment by muyiacc** [comment]
解决了，感谢
