### ISSUE TITLE
不能登录

### ISSUE THREAD

**Issue by TramsWang** [lovechoudoufu/wechat_for_linux#26]
release里的最新版本现在也不能登录了。有更新的安装包吗

**Comment by vhagor** [comment]
![Screenshot from 2024-09-05 23-55-54](https://github.com/user-attachments/assets/d7f954cf-5141-478f-9c61-a04fd3d09cb4)

同问

**Comment by vhagor** [comment]
抱歉，我重新安装就正常了，系统是 ubuntu2024.4

**Comment by TramsWang** [comment]
我的重装了也行了，多谢！
