### ISSUE TITLE
蹲一个flatpak版

### ISSUE THREAD

**Issue by 67906980725** [lovechoudoufu/wechat_for_linux#5]
如题...

**Comment by 67906980725** [comment]
[wechat-universal-flatpak](https://github.com/web1n/wechat-universal-flatpak)

**Comment by landall** [comment]
wechat-universal 就是这个Linux原生版本微信的名字么？

**Comment by 67906980725** [comment]
> wechat-universal 就是这个Linux原生版本微信的名字么？
点进去就是了
